packages:
  - packages/*
  - examples/*
  - docs

linkWorkspacePackages: true
preferWorkspacePackages: true
catalogMode: prefer

onlyBuiltDependencies:
  - esbuild

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vite-plus: 0.2.2
  typescript: ^6.0.0
  typestyles: ^0.8.1
  react: ^19.0.0
  react-dom: ^19.0.0
  react-aria-components: ^1.19.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  '@vitejs/plugin-react': ^5.0.0

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
