/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ThemingIndexRouteImport } from './routes/theming/index';
import { Route as DocsIndexRouteImport } from './routes/docs/index';
import { Route as ComponentsIndexRouteImport } from './routes/components/index';
import { Route as ThemingSlugRouteImport } from './routes/theming/$slug';
import { Route as DocsSlugRouteImport } from './routes/docs/$slug';
import { Route as ComponentsSlugRouteImport } from './routes/components/$slug';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ThemingIndexRoute = ThemingIndexRouteImport.update({
  id: '/theming/',
  path: '/theming/',
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any);
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any);
const ThemingSlugRoute = ThemingSlugRouteImport.update({
  id: '/theming/$slug',
  path: '/theming/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/components/$slug': typeof ComponentsSlugRoute;
  '/docs/$slug': typeof DocsSlugRoute;
  '/theming/$slug': typeof ThemingSlugRoute;
  '/components/': typeof ComponentsIndexRoute;
  '/docs/': typeof DocsIndexRoute;
  '/theming/': typeof ThemingIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/components/$slug': typeof ComponentsSlugRoute;
  '/docs/$slug': typeof DocsSlugRoute;
  '/theming/$slug': typeof ThemingSlugRoute;
  '/components': typeof ComponentsIndexRoute;
  '/docs': typeof DocsIndexRoute;
  '/theming': typeof ThemingIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/components/$slug': typeof ComponentsSlugRoute;
  '/docs/$slug': typeof DocsSlugRoute;
  '/theming/$slug': typeof ThemingSlugRoute;
  '/components/': typeof ComponentsIndexRoute;
  '/docs/': typeof DocsIndexRoute;
  '/theming/': typeof ThemingIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/components/$slug'
    | '/docs/$slug'
    | '/theming/$slug'
    | '/components/'
    | '/docs/'
    | '/theming/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/components/$slug'
    | '/docs/$slug'
    | '/theming/$slug'
    | '/components'
    | '/docs'
    | '/theming';
  id:
    | '__root__'
    | '/'
    | '/components/$slug'
    | '/docs/$slug'
    | '/theming/$slug'
    | '/components/'
    | '/docs/'
    | '/theming/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ComponentsSlugRoute: typeof ComponentsSlugRoute;
  DocsSlugRoute: typeof DocsSlugRoute;
  ThemingSlugRoute: typeof ThemingSlugRoute;
  ComponentsIndexRoute: typeof ComponentsIndexRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
  ThemingIndexRoute: typeof ThemingIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/theming/': {
      id: '/theming/';
      path: '/theming';
      fullPath: '/theming/';
      preLoaderRoute: typeof ThemingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/docs/': {
      id: '/docs/';
      path: '/docs';
      fullPath: '/docs/';
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/components/': {
      id: '/components/';
      path: '/components';
      fullPath: '/components/';
      preLoaderRoute: typeof ComponentsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/theming/$slug': {
      id: '/theming/$slug';
      path: '/theming/$slug';
      fullPath: '/theming/$slug';
      preLoaderRoute: typeof ThemingSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/docs/$slug': {
      id: '/docs/$slug';
      path: '/docs/$slug';
      fullPath: '/docs/$slug';
      preLoaderRoute: typeof DocsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/components/$slug': {
      id: '/components/$slug';
      path: '/components/$slug';
      fullPath: '/components/$slug';
      preLoaderRoute: typeof ComponentsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  DocsSlugRoute: DocsSlugRoute,
  ThemingSlugRoute: ThemingSlugRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ThemingIndexRoute: ThemingIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
