import { atProperty, type TokenSchema } from 'typestyles';

export const colorTokenSchema = {
  background: {
    app: atProperty.color,
    surface: atProperty.color,
    subtle: atProperty.color,
    elevated: atProperty.color,
    popover: atProperty.color,
    muted: atProperty.color,
  },
  text: {
    primary: atProperty.color,
    secondary: atProperty.color,
    onAccent: atProperty.color,
    onDanger: atProperty.color,
    onSuccess: atProperty.color,
    onWarning: atProperty.color,
    onInfo: atProperty.color,
    disabled: atProperty.color,
    placeholder: atProperty.color,
  },
  accent: {
    default: atProperty.color,
    hover: atProperty.color,
    subtle: atProperty.color,
  },
  border: {
    default: atProperty.color,
    strong: atProperty.color,
    focus: atProperty.color,
  },
  shadow: { offset: atProperty.length, color: atProperty.color },
  danger: {
    default: atProperty.color,
    solid: atProperty.color,
    subtle: atProperty.color,
    border: atProperty.color,
  },
  success: {
    default: atProperty.color,
    solid: atProperty.color,
    subtle: atProperty.color,
    border: atProperty.color,
  },
  warning: {
    default: atProperty.color,
    onSolid: atProperty.color,
    subtle: atProperty.color,
    border: atProperty.color,
  },
  info: {
    default: atProperty.color,
    onSolid: atProperty.color,
    subtle: atProperty.color,
    border: atProperty.color,
  },
  link: { default: atProperty.color, hover: atProperty.color },
  ring: { default: atProperty.color },
  overlay: {
    default: atProperty.color,
    backdrop: atProperty.color,
    panel: atProperty.color,
    hover: atProperty.color,
    pressed: atProperty.color,
  },
  skeleton: { default: atProperty.color },
  track: { default: atProperty.color },
  code: {
    base: atProperty.color,
    keyword: atProperty.color,
    title: atProperty.color,
    attr: atProperty.color,
    string: atProperty.color,
    builtIn: atProperty.color,
    comment: atProperty.color,
    name: atProperty.color,
    section: atProperty.color,
    bullet: atProperty.color,
    addition: atProperty.color,
    additionBackground: atProperty.color,
    deletion: atProperty.color,
    deletionBackground: atProperty.color,
  },
} as const satisfies TokenSchema;
