import { designTokens as t, styles, typestyles } from '@var-ui/core';

export const configuratorStyles = typestyles.styles.component(
  'component-configurator',
  () => ({
    slots: [
      'root',
      'workspace',
      'preview',
      'previewInner',
      'controls',
      'controlGroup',
      'controlLabel',
      'toneGrid',
      'appearanceGrid',
      'sizeGrid',
      'toneSwatch',
      'toneSwatchActive',
      'toneCheck',
      'optionButton',
      'optionButtonActive',
      'code',
    ],
    root: {
      marginBlock: '1.5rem',
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3].var,
    },
    workspace: {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) minmax(16rem, 18rem)',
      gap: 0,
      borderRadius: t.radius.lg.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.border.default.var,
      backgroundColor: t.color.background.surface.var,
      overflow: 'hidden',
      ...styles.media('md', 'max', {
        gridTemplateColumns: '1fr',
      }),
    },
    preview: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '12rem',
      padding: t.space[6].var,
      borderRightWidth: t.borderWidth.default.var,
      borderRightStyle: 'solid',
      borderRightColor: t.color.border.default.var,
      backgroundColor: t.color.background.app.var,
      ...styles.media('md', 'max', {
        borderRight: 'none',
        borderBottomWidth: t.borderWidth.default.var,
        borderBottomStyle: 'solid',
        borderBottomColor: t.color.border.default.var,
      }),
    },
    previewInner: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    controls: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[4].var,
      padding: t.space[4].var,
      minWidth: 0,
      backgroundColor: t.color.background.surface.var,
    },
    controlGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[2].var,
    },
    controlLabel: {
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.medium.var,
      color: t.color.text.secondary.var,
    },
    toneGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: t.space[2].var,
    },
    appearanceGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      gap: t.space[2].var,
    },
    sizeGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
      gap: t.space[2].var,
    },
    toneSwatch: {
      position: 'relative',
      aspectRatio: '1',
      borderRadius: t.radius.sm.var,
      borderWidth: t.borderWidth.thick.var,
      borderStyle: 'solid',
      borderColor: 'transparent',
      cursor: 'pointer',
      padding: 0,
      '&:hover': {
        borderColor: t.color.border.strong.var,
      },
      '&:focus-visible': {
        outline: `2px solid ${t.color.border.focus.var}`,
        outlineOffset: '2px',
      },
    },
    toneSwatchActive: {
      position: 'relative',
      aspectRatio: '1',
      borderRadius: t.radius.sm.var,
      borderWidth: t.borderWidth.thick.var,
      borderStyle: 'solid',
      borderColor: t.color.text.primary.var,
      cursor: 'pointer',
      padding: 0,
      '&:focus-visible': {
        outline: `2px solid ${t.color.border.focus.var}`,
        outlineOffset: '2px',
      },
    },
    toneCheck: {
      position: 'absolute',
      inset: 0,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: '#fff',
      fontSize: '0.75rem',
      fontWeight: t.fontWeight.bold.var,
      textShadow: '0 1px 2px rgb(0 0 0 / 40%)',
    },
    optionButton: {
      minWidth: 0,
      minHeight: '2rem',
      borderRadius: t.radius.sm.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.border.default.var,
      backgroundColor: t.color.background.subtle.var,
      color: t.color.text.primary.var,
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.medium.var,
      cursor: 'pointer',
      paddingInline: t.space[2].var,
      paddingBlock: t.space[1].var,
      '&:hover': {
        borderColor: t.color.border.strong.var,
        backgroundColor: t.color.background.elevated.var,
      },
      '&:focus-visible': {
        outline: `2px solid ${t.color.border.focus.var}`,
        outlineOffset: '2px',
      },
    },
    optionButtonActive: {
      minWidth: 0,
      minHeight: '2rem',
      borderRadius: t.radius.sm.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.text.primary.var,
      backgroundColor: t.color.background.elevated.var,
      color: t.color.text.primary.var,
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.semibold.var,
      cursor: 'pointer',
      paddingInline: t.space[2].var,
      paddingBlock: t.space[1].var,
      '&:focus-visible': {
        outline: `2px solid ${t.color.border.focus.var}`,
        outlineOffset: '2px',
      },
    },
    code: {
      borderRadius: t.radius.lg.var,
      overflow: 'hidden',
    },
  }),
  { layer: 'components' },
);
