import { designTokens as t, typestyles } from '@var-ui/core';

export const demoChrome = typestyles.styles.component(
  'demo-chrome',
  () => ({
    slots: [
      'root',
      'card',
      'preview',
      'previewInner',
      'code',
      'codeBlock',
      'codeFade',
      'expand',
      'expandButton',
    ],
    root: {
      marginBlock: '1.5rem',
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[2].var,
    },
    card: {
      borderRadius: t.radius.lg.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.border.default.var,
      backgroundColor: t.color.background.surface.var,
      overflow: 'hidden',
    },
    preview: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '9rem',
      padding: `${t.space[8].var} ${t.space[6].var}`,
      backgroundColor: t.color.background.app.var,
    },
    previewInner: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    code: {
      position: 'relative',
      borderTopWidth: t.borderWidth.default.var,
      borderTopStyle: 'solid',
      borderTopColor: t.color.border.default.var,
    },
    codeBlock: {
      '& [data-codeblock]': {
        border: 'none',
        borderRadius: 0,
        boxShadow: 'none',
        backgroundColor: 'transparent',
      },
      '& [data-codeblock-header]': {
        borderBottomWidth: t.borderWidth.default.var,
        borderBottomStyle: 'solid',
        borderBottomColor: t.color.border.default.var,
        backgroundColor: t.color.background.subtle.var,
      },
      '&[data-demo-framework="react"] [data-codeblock-header] [class*="code-block__title"]::before':
        {
          content: '"TS"',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
          width: '1.25rem',
          height: '1.25rem',
          marginInlineEnd: t.space[2].var,
          borderRadius: t.radius.sm.var,
          fontSize: '0.5625rem',
          fontWeight: t.fontWeight.bold.var,
          fontFamily: t.fontFamily.body.var,
          letterSpacing: '-0.02em',
          lineHeight: 1,
          color: t.color.tone.accent.foregroundOnBackground.var,
          backgroundColor: '#3178c6',
        },
      '&[data-demo-framework="astro"] [data-codeblock-header] [class*="code-block__title"]::before':
        {
          content: '"A"',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
          width: '1.25rem',
          height: '1.25rem',
          marginInlineEnd: t.space[2].var,
          borderRadius: t.radius.sm.var,
          fontSize: '0.625rem',
          fontWeight: t.fontWeight.bold.var,
          fontFamily: t.fontFamily.body.var,
          lineHeight: 1,
          color: t.color.tone.accent.foregroundOnBackground.var,
          backgroundColor: '#ff5d01',
        },
      '&[data-demo-framework="html"] [data-codeblock-header] [class*="code-block__title"]::before':
        {
          content: '"5"',
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          flexShrink: 0,
          width: '1.25rem',
          height: '1.25rem',
          marginInlineEnd: t.space[2].var,
          borderRadius: t.radius.sm.var,
          fontSize: '0.5625rem',
          fontWeight: t.fontWeight.bold.var,
          fontFamily: t.fontFamily.body.var,
          lineHeight: 1,
          color: t.color.tone.accent.foregroundOnBackground.var,
          backgroundColor: '#e34c26',
        },
      '& [data-codeblock-header] [class*="code-block__title"]': {
        display: 'inline-flex',
        alignItems: 'center',
      },
      '& [data-codeblock-header] [class*="code-block__language"]': {
        display: 'none',
      },
      // '& [data-codeblock-body]': {
      //   backgroundColor: t.color.background.subtle.var,
      //   transition: 'max-height 0.2s ease',
      // },
      '& [data-codeblock-copy-text]': {
        position: 'absolute',
        width: '1px',
        height: '1px',
        padding: 0,
        margin: '-1px',
        overflow: 'hidden',
        clip: 'rect(0, 0, 0, 0)',
        whiteSpace: 'nowrap',
        border: 0,
      },
    },
    codeFade: {
      position: 'absolute',
      insetInline: 0,
      bottom: '2.75rem',
      height: '3.5rem',
      pointerEvents: 'none',
      background: `linear-gradient(to bottom, transparent, ${t.color.background.surface.var})`,
    },
    expand: {
      display: 'flex',
      justifyContent: 'center',
      paddingBlock: t.space[2].var,
      borderTopWidth: t.borderWidth.default.var,
      borderTopStyle: 'solid',
      borderTopColor: t.color.border.default.var,
      // backgroundColor: t.color.background.subtle.var,
    },
    expandButton: {
      appearance: 'none',
      border: 'none',
      background: 'transparent',
      padding: `${t.space[1].var} ${t.space[3].var}`,
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.medium.var,
      fontFamily: 'inherit',
      color: t.color.tone.accent.foreground.var,
      cursor: 'pointer',
      borderRadius: t.radius.sm.var,
      '&:hover': {
        textDecoration: 'underline',
      },
      '&:focus-visible': {
        outline: `2px solid ${t.color.border.focus.var}`,
        outlineOffset: '2px',
      },
    },
  }),
  { layer: 'components' },
);
