import { designTokens as t, styles } from '@var-ui/core';

const headerHeight = '3.5rem';
const sidebarWidth = '15rem';
const tocWidth = '12.5rem';

export const docsShell = styles.component(
  'docs-shell',
  () => ({
    slots: [
      'root',
      'header',
      'headerInner',
      'headerLogo',
      'headerLogoText',
      'headerNav',
      'headerNavLink',
      'headerNavLinkActive',
      'headerIconButton',
      'colorModeGroup',
      'colorModeButton',
      'colorModeButtonActive',
      'headerMenuButton',
      'body',
      'sidebar',
      'sidebarInner',
      'sidebarGroup',
      'sidebarGroupLabel',
      'sidebarList',
      'sidebarLink',
      'sidebarLinkActive',
      'main',
      'mainInner',
      'toc',
      'tocInner',
      'tocTitle',
      'tocList',
      'tocLink',
      'tocLinkActive',
      'tocLinkNested',
      'mobileNavOverlay',
      'mobileNavPanel',
    ],
    root: {
      minHeight: '100dvh',
      '--docs-header-height': headerHeight,
      '--docs-sidebar-width': sidebarWidth,
      '--docs-toc-width': tocWidth,
    },
    header: {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 40,
      height: headerHeight,
      borderBottom: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.background.surface,
    },
    headerInner: {
      width: '100%',
      height: '100%',
      maxWidth: '100%',
      paddingInline: t.space[4],
    },
    headerLogo: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: t.space[2],
      color: t.color.text.primary,
      textDecoration: 'none',
      fontWeight: t.fontWeight.semibold,
    },
    headerLogoText: {
      fontSize: t.fontSize.md,
      fontWeight: t.fontWeight.semibold,
      lineHeight: 1,
      fontFamily: t.fontFamily.mono,
    },
    headerNav: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[1],
      listStyle: 'none',
      margin: 0,
      padding: 0,
    },
    headerNavLink: {
      display: 'inline-flex',
      alignItems: 'center',
      height: '2rem',
      paddingInline: t.space[2],
      borderRadius: t.radius.sm,
      color: t.color.text.secondary,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.medium,
      textDecoration: 'none',
      '&:hover': {
        color: t.color.text.primary,
        backgroundColor: t.color.background.subtle,
      },
    },
    headerNavLinkActive: {
      display: 'inline-flex',
      alignItems: 'center',
      height: '2rem',
      paddingInline: t.space[2],
      borderRadius: t.radius.sm,
      color: t.color.text.primary,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      textDecoration: 'none',
      backgroundColor: t.color.background.subtle,
    },
    headerIconButton: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '2.25rem',
      height: '2.25rem',
      borderRadius: t.radius.sm,
      color: t.color.text.primary,
      textDecoration: 'none',
    },
    colorModeGroup: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '2px',
      padding: '2px',
      borderRadius: t.radius.sm,
      backgroundColor: t.color.background.subtle,
    },
    colorModeButton: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '1.75rem',
      height: '1.75rem',
      borderRadius: t.radius.sm,
      color: t.color.text.secondary,
    },
    colorModeButtonActive: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '1.75rem',
      height: '1.75rem',
      borderRadius: t.radius.sm,
      color: t.color.text.primary,
      backgroundColor: t.color.background.surface,
      boxShadow: `0 0 0 1px ${t.color.border.default}`,
    },
    headerMenuButton: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '2.25rem',
      height: '2.25rem',
      borderRadius: t.radius.sm,
      color: t.color.text.primary,
      border: 'none',
      background: 'transparent',
      cursor: 'pointer',
      '@media (min-width: 768px)': {
        display: 'none',
      },
    },
    body: {
      display: 'grid',
      gridTemplateColumns: `${sidebarWidth} minmax(0, 1fr)`,
      gap: t.space[6],
      paddingTop: `calc(${headerHeight} + ${t.space[6]})`,
      paddingInline: t.space[4],
      paddingBottom: t.space[8],
      maxWidth: '90rem',
      marginInline: 'auto',
      '@media (min-width: 1024px)': {
        gridTemplateColumns: `${sidebarWidth} minmax(0, 1fr) ${tocWidth}`,
      },
    },
    sidebar: {
      display: 'none',
      '@media (min-width: 768px)': {
        display: 'block',
        position: 'sticky',
        top: `calc(${headerHeight} + ${t.space[4]})`,
        alignSelf: 'start',
        maxHeight: `calc(100dvh - ${headerHeight} - ${t.space[8]})`,
        overflowY: 'auto',
      },
    },
    sidebarInner: {
      paddingRight: t.space[2],
    },
    sidebarGroup: {
      '& + &': {
        marginTop: t.space[4],
      },
    },
    sidebarGroupLabel: {
      margin: 0,
      marginBottom: t.space[2],
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      color: t.color.text.secondary,
    },
    sidebarList: {
      listStyle: 'none',
      margin: 0,
      padding: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[1],
    },
    sidebarLink: {
      display: 'block',
      paddingBlock: t.space[1],
      paddingInline: t.space[2],
      borderRadius: t.radius.sm,
      color: t.color.text.secondary,
      fontSize: t.fontSize.sm,
      textDecoration: 'none',
      '&:hover': {
        color: t.color.text.primary,
        backgroundColor: t.color.background.subtle,
      },
    },
    sidebarLinkActive: {
      display: 'block',
      paddingBlock: t.space[1],
      paddingInline: t.space[2],
      borderRadius: t.radius.sm,
      color: t.color.text.primary,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      textDecoration: 'none',
      backgroundColor: t.color.background.subtle,
    },
    main: {
      minWidth: 0,
    },
    mainInner: {
      maxWidth: '48rem',
      marginInline: 'auto',
    },
    toc: {
      display: 'none',
      '@media (min-width: 1024px)': {
        display: 'block',
        position: 'sticky',
        top: `calc(${headerHeight} + ${t.space[4]})`,
        alignSelf: 'start',
        maxHeight: `calc(100dvh - ${headerHeight} - ${t.space[8]})`,
        overflowY: 'auto',
      },
    },
    tocInner: {
      paddingLeft: t.space[2],
      borderLeft: `1px solid ${t.color.border.default}`,
    },
    tocTitle: {
      margin: 0,
      marginBottom: t.space[2],
      fontSize: t.fontSize.xs,
      fontWeight: t.fontWeight.semibold,
      letterSpacing: '0.04em',
      textTransform: 'uppercase',
      color: t.color.text.secondary,
    },
    tocList: {
      listStyle: 'none',
      margin: 0,
      padding: 0,
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[1],
    },
    tocLink: {
      display: 'block',
      fontSize: t.fontSize.sm,
      color: t.color.text.secondary,
      textDecoration: 'none',
      '&:hover': {
        color: t.color.text.primary,
      },
    },
    tocLinkActive: {
      display: 'block',
      fontSize: t.fontSize.sm,
      color: t.color.text.primary,
      fontWeight: t.fontWeight.semibold,
      textDecoration: 'none',
    },
    tocLinkNested: {
      paddingLeft: t.space[3],
    },
    mobileNavOverlay: {
      position: 'fixed',
      inset: 0,
      zIndex: 50,
      backgroundColor: 'rgba(0, 0, 0, 0.4)',
      '@media (min-width: 768px)': {
        display: 'none',
      },
    },
    mobileNavPanel: {
      position: 'fixed',
      top: headerHeight,
      left: 0,
      bottom: 0,
      zIndex: 51,
      width: 'min(18rem, 85vw)',
      padding: t.space[4],
      overflowY: 'auto',
      backgroundColor: t.color.background.surface,
      borderRight: `1px solid ${t.color.border.default}`,
      '@media (min-width: 768px)': {
        display: 'none',
      },
    },
  }),
  { layer: 'utilities' },
);
