import { designTokens as t, typestyles } from '@var-ui/core';

export const homeBento = typestyles.styles.component(
  'home-bento',
  () => ({
    slots: [
      'switcher',
      'switcherPill',
      'switcherPillActive',
      'switcherSwatch',
      'showcase',
      'grid',
      'tile',
      'tileSpan2',
      'tileRowSpan2',
      'tileSpanFull',
    ],
    switcher: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: t.space[2].var,
      marginBottom: t.space[4].var,
    },
    switcherPill: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: t.space[2].var,
      height: '2.25rem',
      paddingInline: t.space[3].var,
      borderRadius: t.radius.sm.var,
      border: `1px solid ${t.color.border.default.var}`,
      backgroundColor: t.color.background.surface.var,
      color: t.color.text.secondary.var,
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.medium.var,
      cursor: 'pointer',
      '&:hover': {
        color: t.color.text.primary.var,
        backgroundColor: t.color.background.subtle.var,
      },
    },
    switcherPillActive: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: t.space[2].var,
      height: '2.25rem',
      paddingInline: t.space[3].var,
      borderRadius: t.radius.sm.var,
      border: `1px solid ${t.color.accent.default.var}`,
      backgroundColor: t.color.background.subtle.var,
      color: t.color.text.primary.var,
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.semibold.var,
      cursor: 'pointer',
    },
    switcherSwatch: {
      display: 'inline-block',
      width: '0.75rem',
      height: '0.75rem',
      borderRadius: '999px',
      border: `1px solid ${t.color.border.default.var}`,
      flexShrink: 0,
    },
    showcase: {
      borderRadius: t.radius.lg.var,
      border: `1px solid ${t.color.border.default.var}`,
      backgroundColor: t.color.background.app.var,
      padding: t.space[4].var,
      marginBottom: t.space[8].var,
    },
    grid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
      gridAutoFlow: 'dense',
      gap: t.space[4].var,
      '@media (max-width: 768px)': {
        gridTemplateColumns: '1fr',
      },
    },
    tile: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3].var,
      minWidth: 0,
      borderRadius: t.radius.md.var,
      border: `1px solid ${t.color.border.default.var}`,
      backgroundColor: t.color.background.surface.var,
      padding: t.space[4].var,
      overflow: 'hidden',
    },
    tileSpan2: {
      gridColumn: 'span 2',
      '@media (max-width: 768px)': {
        gridColumn: 'span 1',
      },
    },
    tileRowSpan2: {
      gridRow: 'span 2',
    },
    tileSpanFull: {
      gridColumn: '1 / -1',
    },
  }),
  { layer: 'utilities' },
);
