import { designTokens as t, styles } from '@var-ui/core';

export const homeBento = styles.component(
  'home-bento',
  () => ({
    slots: [
      'switcher',
      'switcherPill',
      'switcherPillActive',
      'switcherSwatch',
      'showcase',
      'grid',
      'tile',
      'tileSpan2',
      'tileRowSpan2',
      'tileSpanFull',
    ],
    switcher: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: t.space[2],
      marginBottom: t.space[4],
    },
    switcherPill: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: t.space[2],
      height: '2.25rem',
      paddingInline: t.space[3],
      borderRadius: t.radius.sm,
      border: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.background.surface,
      color: t.color.text.secondary,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.medium,
      cursor: 'pointer',
      '&:hover': {
        color: t.color.text.primary,
        backgroundColor: t.color.background.subtle,
      },
    },
    switcherPillActive: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: t.space[2],
      height: '2.25rem',
      paddingInline: t.space[3],
      borderRadius: t.radius.sm,
      border: `1px solid ${t.color.accent.default}`,
      backgroundColor: t.color.background.subtle,
      color: t.color.text.primary,
      fontSize: t.fontSize.sm,
      fontWeight: t.fontWeight.semibold,
      cursor: 'pointer',
    },
    switcherSwatch: {
      display: 'inline-block',
      width: '0.75rem',
      height: '0.75rem',
      borderRadius: '999px',
      border: `1px solid ${t.color.border.default}`,
      flexShrink: 0,
    },
    showcase: {
      borderRadius: t.radius.lg,
      border: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.background.app,
      padding: t.space[4],
      marginBottom: t.space[8],
    },
    grid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
      gridAutoFlow: 'dense',
      gap: t.space[4],
      '@media (max-width: 768px)': {
        gridTemplateColumns: '1fr',
      },
    },
    tile: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3],
      minWidth: 0,
      borderRadius: t.radius.md,
      border: `1px solid ${t.color.border.default}`,
      backgroundColor: t.color.background.surface,
      padding: t.space[4],
      overflow: 'hidden',
    },
    tileSpan2: {
      gridColumn: 'span 2',
      '@media (max-width: 768px)': {
        gridColumn: 'span 1',
      },
    },
    tileRowSpan2: {
      gridRow: 'span 2',
    },
    tileSpanFull: {
      gridColumn: '1 / -1',
    },
  }),
  { layer: 'utilities' },
);
