import { designTokens as t, typestyles } from '@var-ui/core';

export const shadowSwatchesStyles = typestyles.styles.component(
  'shadow-swatches',
  () => ({
    slots: [
      'root',
      'section',
      'sectionTitle',
      'sectionDescription',
      'grid',
      'card',
      'preview',
      'previewSurface',
      'meta',
      'token',
      'cssVar',
    ],
    root: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[8].var,
      marginBlock: '1.5rem',
    },
    section: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[1].var,
    },
    sectionTitle: {
      margin: 0,
      fontSize: t.fontSize.lg.var,
      fontWeight: t.fontWeight.semibold.var,
      color: t.color.text.primary.var,
    },
    sectionDescription: {
      margin: 0,
      fontSize: t.fontSize.sm.var,
      color: t.color.text.secondary.var,
      lineHeight: t.lineHeight.relaxed.var,
    },
    grid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(11rem, 1fr))',
      gap: t.space[3].var,
    },
    card: {
      display: 'flex',
      flexDirection: 'column',
      borderRadius: t.radius.md.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.border.default.var,
      overflow: 'hidden',
      backgroundColor: t.color.background.surface.var,
    },
    preview: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '6.5rem',
      padding: t.space[5].var,
      backgroundColor: t.color.background.subtle.var,
      borderBottomWidth: t.borderWidth.default.var,
      borderBottomStyle: 'solid',
      borderBottomColor: t.color.border.default.var,
    },
    previewSurface: {
      width: '4.5rem',
      height: '3rem',
      borderRadius: t.radius.sm.var,
      backgroundColor: t.color.background.surface.var,
    },
    meta: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[1].var,
      padding: t.space[2].var,
    },
    token: {
      fontSize: t.fontSize.xs.var,
      fontWeight: t.fontWeight.medium.var,
      color: t.color.text.primary.var,
      fontFamily: t.fontFamily.mono.var,
      wordBreak: 'break-word',
    },
    cssVar: {
      fontSize: t.fontSize.xs.var,
      color: t.color.text.secondary.var,
      fontFamily: t.fontFamily.mono.var,
      wordBreak: 'break-all',
    },
  }),
  { layer: 'components' },
);
