import { designTokens as t, typestyles } from '@var-ui/core';

export const themePlaygroundStyles = typestyles.styles.component(
  'theme-playground',
  () => ({
    slots: [
      'root',
      'workspace',
      'preview',
      'previewInner',
      'previewFrame',
      'previewFrameMobile',
      'toolbar',
      'code',
      'controlGroup',
      'controlLabel',
      'controlTabs',
      'baseStyles',
      'colorList',
      'colorField',
      'colorFieldLabel',
      'colorRow',
      'colorSwatch',
      'deferredTab',
    ],
    root: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3].var,
      height: '100%',
      minHeight: 0,
    },
    workspace: {
      display: 'flex',
      flexDirection: 'column',
      flex: 1,
      minHeight: 0,
      backgroundColor: t.color.background.surface.var,
      overflow: 'hidden',
    },
    preview: {
      display: 'flex',
      flexDirection: 'column',
      flex: 1,
      minHeight: 0,
      backgroundColor: t.color.background.app.var,
    },
    toolbar: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: t.space[2].var,
      padding: t.space[3].var,
      borderBottomWidth: t.borderWidth.default.var,
      borderBottomStyle: 'solid',
      borderBottomColor: t.color.border.default.var,
    },
    previewInner: {
      flex: 1,
      minHeight: 0,
      padding: t.space[4].var,
      overflow: 'auto',
    },
    previewFrame: {
      width: '100%',
    },
    previewFrameMobile: {
      width: '100%',
      maxWidth: '24rem',
      marginInline: 'auto',
    },
    controlGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[2].var,
    },
    controlLabel: {
      fontSize: t.fontSize.sm.var,
      fontWeight: t.fontWeight.medium.var,
      color: t.color.text.secondary.var,
    },
    controlTabs: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3].var,
      minHeight: 0,
    },
    baseStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[4].var,
    },
    colorList: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[3].var,
    },
    colorField: {
      display: 'flex',
      flexDirection: 'column',
      gap: t.space[1].var,
    },
    colorFieldLabel: {
      fontSize: t.fontSize.xs.var,
      color: t.color.text.secondary.var,
    },
    colorRow: {
      display: 'flex',
      alignItems: 'center',
      gap: t.space[2].var,
    },
    colorSwatch: {
      width: '1.5rem',
      height: '1.5rem',
      borderRadius: t.radius.sm.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.border.default.var,
      flexShrink: 0,
    },
    deferredTab: {
      fontSize: t.fontSize.sm.var,
      color: t.color.text.secondary.var,
      lineHeight: t.lineHeight.relaxed.var,
    },
    code: {
      flexShrink: 0,
      height: '14rem',
      maxHeight: '14rem',
      borderRadius: t.radius.lg.var,
      borderWidth: t.borderWidth.default.var,
      borderStyle: 'solid',
      borderColor: t.color.border.default.var,
      overflow: 'hidden',
      '& [data-codeblock]': {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        maxHeight: '100%',
        border: 'none',
        boxShadow: 'none',
        borderRadius: 0,
      },
      '& [data-codeblock-header]': {
        flexShrink: 0,
      },
      '& [data-codeblock-body]': {
        flex: 1,
        minHeight: 0,
        overflow: 'auto',
      },
    },
  }),
  { layer: 'components' },
);
